global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'firefly'
    static_configs:
      - targets: ['firefly:9090']

  - job_name: 'ethereum'
    static_configs:
      - targets: ['ethereum:5000']

  - job_name: 'ipfs'
    static_configs:
      - targets: ['ipfs:5001']
